apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quayio-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed: "true"
    notifications.argoproj.io/subscribe.on-rollback: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/Erkadaflown/k8s_config
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sictedu22
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
  rollback:
    enabled: true
    force: false
    recreate: false
  healthChecks:
    - kind: Deployment
      apiVersion: apps/v1
      name: "*"
      failureThreshold: 3