apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quayio-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Erkadaflown/k8s_config
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sictedu22
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true