apiVersion: v1
kind: Service
metadata:
  name: quayio-deployment-service
  namespace: sictedu22
spec:
  selector:
    app: quayio-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31667
  type: NodePort